'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'bn' | 'en';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations = {
    bn: {
        // Navigation
        'nav.features': 'বৈশিষ্ট্যসমূহ',
        'nav.products': 'ব্লগ',
        'nav.resources': 'সম্পদ',
        'nav.contact': 'যোগাযোগ',
        'nav.startForFree': 'বিনামূল্যে শুরু করুন',
        'nav.getStarted': 'শুরু করুন',
        'nav.login': 'লগইন',
        'nav.signUp': 'সাইন আপ',

        // Hero Section
        'hero.title': 'জাপানি ভাষা শিক্ষার সেরা প্ল্যাটফর্ম',
        'hero.subtitle': 'আমাদের আধুনিক প্ল্যাটফর্মে জাপানি ভাষা শিখুন। হিরাগানা থেকে কাঞ্জি পর্যন্ত সম্পূর্ণ কোর্স।',
        'hero.cta': 'আজই শুরু করুন',
        'hero.watchDemo': 'ডেমো দেখুন',

        // Features Section
        'features.title': 'আমাদের বৈশিষ্ট্যসমূহ',
        'features.subtitle': 'জাপানি ভাষা শেখার জন্য প্রয়োজনীয় সব কিছু',
        'features.interactive.title': 'ইন্টারঅ্যাক্টিভ লেসন',
        'features.interactive.description': 'আকর্ষণীয় ইন্টারঅ্যাক্টিভ লেসনের মাধ্যমে জাপানি ভাষা শিখুন',
        'features.progress.title': 'অগ্রগতি ট্র্যাকিং',
        'features.progress.description': 'আপনার শেখার অগ্রগতি দেখুন এবং লক্ষ্য অর্জন করুন',
        'features.community.title': 'কমিউনিটি সাপোর্ট',
        'features.community.description': 'অন্যান্য শিক্ষার্থীদের সাথে যোগ দিন এবং একসাথে শিখুন',

        // Courses Section
        'courses.title': 'আমাদের কোর্সগুলি',
        'courses.subtitle': 'আপনার স্তর অনুযায়ী উপযুক্ত কোর্স বেছে নিন',
        'courses.beginner': 'শিক্ষানবিস',
        'courses.intermediate': 'মধ্যম',
        'courses.advanced': 'উন্নত',
        'courses.enrollNow': 'এখনই ভর্তি হন',
        'courses.viewDetails': 'বিস্তারিত দেখুন',

        // Pricing Section
        'pricing.title': 'মূল্য পরিকল্পনা',
        'pricing.subtitle': 'আপনার বাজেট অনুযায়ী সেরা প্যাকেজ বেছে নিন',
        'pricing.free': 'ফ্রি',
        'pricing.premium': 'প্রিমিয়াম',
        'pricing.month': '/মাস',
        'pricing.year': '/বছর',
        'pricing.choosePlan': 'প্ল্যান বেছে নিন',
        'pricing.noCreditCard': 'কোন ক্রেডিট কার্ড প্রয়োজন নেই',
        'pricing.upgradeAnytime': 'যেকোনো সময় আপগ্রেড করুন • কোন বাধ্যবাধকতা নেই',
        'pricing.cancelAnytime': 'যেকোনো সময় বাতিল করুন • ৩০ দিনের মানি-ব্যাক গ্যারান্টি',
        'pricing.oneTimePayment': 'এক-বার পেমেন্ট • আজীবন আপডেট অন্তর্ভুক্ত',
        'pricing.guarantee': '৩০ দিনের মানি-ব্যাক গ্যারান্টি',
        'pricing.securePayment': 'নিরাপদ পেমেন্ট প্রক্রিয়া',
        'pricing.satisfiedLearners': '১০,০০০+ সন্তুষ্ট শিক্ষার্থী',
        'pricing.trustText': 'হাজার হাজার সফল জাপানি ভাষা শিক্ষার্থীদের সাথে যোগ দিন যারা আমাদের প্রমাণিত পদ্ধতি এবং বিশেষজ্ঞ গাইড দিয়ে তাদের ভাষার দক্ষতা রূপান্তরিত করেছেন।',

        // Footer Section
        'footer.newsletter.title': 'জাপানি ভাষা শেখার টিপস দিয়ে আপডেট থাকুন',
        'footer.newsletter.subtitle': 'সাপ্তাহিক অন্তর্দৃষ্টি, অধ্যয়ন টিপস, এবং এক্সক্লুসিভ কন্টেন্ট আপনার ইনবক্সে পান।',
        'footer.newsletter.community': 'আমাদের উৎসাহী জাপানি ভাষা শিক্ষার্থীদের কমিউনিটিতে যোগ দিন!',
        'footer.newsletter.placeholder': 'আপনার ইমেইল ঠিকানা দিন',
        'footer.newsletter.subscribe': 'সাবস্ক্রাইব',
        'footer.newsletter.noSpam': 'কোন স্প্যাম নেই, যেকোনো সময় আনসাবস্ক্রাইব করুন। ১০,০০০+ সাবস্ক্রাইবার আমাদের বিশ্বাস করেন।',
        'footer.brand.description': 'আমাদের ব্যাপক অনলাইন কোর্স, AI-চালিত অনুশীলন, এবং বিশেষজ্ঞ গাইডেন্স দিয়ে জাপানি ভাষায় দক্ষতা অর্জন করুন। আজই আপনার ভাষা শেখার যাত্রা রূপান্তরিত করুন।',
        'footer.contact.email': 'support@japaneseshikhi.com',
        'footer.contact.phone': '+১ (৫৫৫) ১২৩-৪৫৬৭',
        'footer.contact.available': 'বিশ্বব্যাপী উপলব্ধ',
        'footer.rating': '৪.৯/৫ রেটিং',
        'footer.students': '১০,০০০+ শিক্ষার্থী',
        'footer.certified': 'সার্টিফাইড শিক্ষক',
        'footer.quickLinks': 'দ্রুত লিংক',
        'footer.courses': 'কোর্সগুলি',
        'footer.support': 'সহায়তা',
        'footer.followUs': 'আমাদের ফলো করুন',
        'footer.aboutUs': 'আমাদের সম্পর্কে',
        'footer.howItWorks': 'এটি কিভাবে কাজ করে',
        'footer.successStories': 'সাফল্যের গল্প',
        'footer.blog': 'ব্লগ',
        'footer.beginnerJapanese': 'শিক্ষানবিস জাপানি',
        'footer.intermediateJapanese': 'মধ্যম জাপানি',
        'footer.advancedJapanese': 'উন্নত জাপানি',
        'footer.businessJapanese': 'ব্যবসায়িক জাপানি',
        'footer.jlptPreparation': 'JLPT প্রস্তুতি',
        'footer.conversationPractice': 'কথোপকথন অনুশীলন',
        'footer.popular': 'জনপ্রিয়',
        'footer.new': 'নতুন',
        'footer.helpCenter': 'সহায়তা কেন্দ্র',
        'footer.contactSupport': 'সহায়তার জন্য যোগাযোগ',
        'footer.communityForum': 'কমিউনিটি ফোরাম',
        'footer.privacyPolicy': 'গোপনীয়তা নীতি',
        'footer.termsOfService': 'সেবার শর্তাবলী',
        'footer.refundPolicy': 'রিফান্ড নীতি',
        'footer.copyright': '© ২০২৫ জাপানিজ শিখি। সমস্ত অধিকার সংরক্ষিত।',
        'footer.madeWith': 'জাপানি ভাষা শিক্ষার্থীদের জন্য ভালোবাসা দিয়ে তৈরি',
        'footer.privacyLink': 'গোপনীয়তা',
        'footer.termsLink': 'শর্তাবলী',
        'footer.cookies': 'কুকিজ',

        // Testimonials
        'testimonials.title': 'শিক্ষার্থীদের মতামত',
        'testimonials.subtitle': 'আমাদের সফল শিক্ষার্থীরা কী বলছেন',

        // Footer
        'footer.company': 'কোম্পানি',
        'footer.about': 'আমাদের সম্পর্কে',
        'footer.careers': 'ক্যারিয়ার',
        'footer.contact': 'যোগাযোগ',
        'footer.help': 'সহায়তা',
        'footer.faq': 'প্রশ্ন ও উত্তর',
        'footer.community': 'কমিউনিটি',
        'footer.legal': 'আইনি',
        'footer.privacy': 'গোপনীয়তা নীতি',
        'footer.terms': 'ব্যবহারের শর্ত',
        'footer.allRightsReserved': 'সর্বস্বত্ব সংরক্ষিত',

        // Admin Dashboard
        'admin.dashboard': 'ড্যাশবোর্ড',
        'admin.dashboardOverview': 'আপনার জাপানি ভাষার কোর্সগুলির সংক্ষিপ্ত বিবরণ',
        'admin.totalCourses': 'মোট কোর্স',
        'admin.totalStudents': 'মোট শিক্ষার্থী',
        'admin.totalRevenue': 'মোট আয়',
        'admin.courseCompletion': 'কোর্স সম্পূর্ণতা',
        'admin.coursesCreated': 'কোর্স তৈরি হয়েছে',
        'admin.studentsEnrolled': 'শিক্ষার্থী ভর্তি হয়েছে',
        'admin.noRevenue': 'কোনো আয় হয়নি',
        'admin.noCompletions': 'এখনও কোনো সম্পূর্ণতা নেই',
        'admin.noCoursesCreated': 'এখনও কোনো কোর্স তৈরি হয়নি',
        'admin.noEnrollments': 'এখনও কোনো ভর্তি হয়নি',
        'admin.recentActivity': 'সাম্প্রতিক কার্যকলাপ',
        'admin.latestActivity': 'সর্বশেষ কোর্স এবং শিক্ষার্থীদের কার্যকলাপ',
        'admin.noRecentActivity': 'প্রদর্শনের জন্য কোনো সাম্প্রতিক কার্যকলাপ নেই',
        'admin.japaneseShikhi': 'জাপানিজ শিখি',
        'admin.adminPanel': 'অ্যাডমিন প্যানেল',
        'admin.welcome': 'স্বাগতম',
        'admin.home': 'হোম',
        'admin.users': 'ব্যবহারকারী',
        'admin.courses': 'কোর্সগুলি',
        'admin.students': 'শিক্ষার্থীরা',
        'admin.analytics': 'বিশ্লেষণ',
        'admin.settings': 'সেটিংস',
        'admin.createCourse': 'নতুন কোর্স তৈরি করুন',
        'admin.editCourse': 'কোর্স সম্পাদনা করুন',
        'admin.courseTitle': 'কোর্সের শিরোনাম',
        'admin.courseDescription': 'কোর্সের বিবরণ',
        'admin.save': 'সংরক্ষণ করুন',
        'admin.cancel': 'বাতিল',
        'admin.delete': 'মুছে ফেলুন',

        // Users Page
        'users.title': 'শিক্ষার্থী ও ব্যবহারকারী',
        'users.subtitle': 'ভর্তি শিক্ষার্থীদের পরিচালনা করুন এবং তাদের অগ্রগতি ট্র্যাক করুন',
        'users.exportData': 'ডেটা রপ্তানি করুন',
        'users.sendNotification': 'বিজ্ঞপ্তি পাঠান',
        'users.totalUsers': 'মোট ব্যবহারকারী',
        'users.activeUsers': 'সক্রিয় ব্যবহারকারী',
        'users.premiumUsers': 'প্রিমিয়াম ব্যবহারকারী',
        'users.noUsersYet': 'এখনও কোনো ব্যবহারকারী নেই',
        'users.noActiveUsers': 'কোনো সক্রিয় ব্যবহারকারী নেই',
        'users.noPremiumUsers': 'কোনো প্রিমিয়াম ব্যবহারকারী নেই',
        'users.noRevenueYet': 'এখনও কোনো আয় নেই',
        'users.searchAndFilter': 'ব্যবহারকারী অনুসন্ধান ও ফিল্টার করুন',
        'users.searchUsers': 'ব্যবহারকারী অনুসন্ধান',
        'users.searchPlaceholder': 'নাম বা ইমেইল দিয়ে অনুসন্ধান করুন...',
        'users.status': 'অবস্থা',
        'users.subscription': 'সাবস্ক্রিপশন',
        'users.allStatus': 'সব অবস্থা',
        'users.allTypes': 'সব ধরণ',
        'users.active': 'সক্রিয়',
        'users.inactive': 'নিষ্ক্রিয়',
        'users.free': 'বিনামূল্যে',
        'users.premium': 'প্রিমিয়াম',
        'users.allUsers': 'সব ব্যবহারকারী',
        'users.enrollmentTracking': 'শিক্ষার্থী ভর্তি এবং অগ্রগতি ট্র্যাকিং',
        'users.noUsersFound': 'কোনো ব্যবহারকারী খুঁজে পাওয়া যায়নি',
        'users.willAppearHere': 'ব্যবহারকারীরা আপনার কোর্সে সাইন আপ করলে এখানে দেখা যাবে',
        'users.exporting': 'রপ্তানি করা হচ্ছে...',
        'users.exportSuccess': 'সফলভাবে ডেটা রপ্তানি করা হয়েছে',
        'users.exportTemplateSuccess': 'টেমপ্লেট সফলভাবে ডাউনলোড হয়েছে',
        'users.exportError': 'ডেটা রপ্তানি করতে ত্রুটি হয়েছে',
        'users.users': 'ব্যবহারকারী',
        'users.activeUsersText': 'সক্রিয় ব্যবহারকারী',
        'users.premiumUsersText': 'প্রিমিয়াম ব্যবহারকারী',
        'users.revenueGenerated': 'আয় হয়েছে',

        // Course Management
        'course.management': 'কোর্স পরিচালনা',
        'course.createAndManage': 'জাপানি কোর্স তৈরি এবং পরিচালনা করুন',
        'course.addNewCourse': 'নতুন কোর্স যোগ করুন',
        'course.createNewCourse': 'নতুন কোর্স তৈরি করুন',
        'course.basicDetails': 'আপনার কোর্সের মৌলিক তথ্য',
        'course.courseTitle': 'কোর্সের শিরোনাম',
        'course.titlePlaceholder': 'যেমন, শিক্ষানবিস জাপানি ব্যাকরণ',
        'course.level': 'স্তর',
        'course.beginner': 'শিক্ষানবিস',
        'course.intermediate': 'মধ্যম',
        'course.advanced': 'উন্নত',
        'course.description': 'বিবরণ',
        'course.descriptionPlaceholder': 'শিক্ষার্থীরা এই কোর্সে কী শিখবেন তা বর্ণনা করুন...',
        'course.difficulty': 'কঠিনতা',
        'course.easy': 'সহজ',
        'course.medium': 'মধ্যম',
        'course.hard': 'কঠিন',
        'course.cancel': 'বাতিল',
        'course.createCourse': 'কোর্স তৈরি করুন',
        'course.allCourses': 'সব কোর্স',
        'course.manageCatalog': 'আপনার কোর্স ক্যাটালগ পরিচালনা করুন এবং ভর্তি ট্র্যাক করুন',
        'course.noCoursesFound': 'কোনো কোর্স পাওয়া যায়নি। শুরু করতে আপনার প্রথম কোর্স তৈরি করুন।',
        'course.published': 'প্রকাশিত',
        'course.draft': 'খসড়া',
        'course.students': 'শিক্ষার্থী',
        'course.created': 'তৈরি',
        'course.view': 'দেখুন',
        'course.edit': 'সম্পাদনা',
        'course.delete': 'মুছুন',
        'course.details': 'কোর্সের বিস্তারিত',
        'course.modules': 'ক্লাস মডিউল',
        'course.classLinks': 'ক্লাস লিংক',
        'course.resources': 'সম্পদ ও ইউটিউব',
        'course.enrolledStudents': 'ভর্তি শিক্ষার্থী',
        'course.assignments': 'অ্যাসাইনমেন্ট ও কুইজ',
        'course.addModule': 'মডিউল যোগ করুন',
        'course.addClassLink': 'ক্লাস লিংক যোগ করুন',
        'course.addResource': 'সম্পদ যোগ করুন',
        'course.moduleTitle': 'মডিউলের শিরোনাম',
        'course.moduleContent': 'মডিউলের বিষয়বস্তু',
        'course.moduleOrder': 'মডিউলের ক্রম',
        'course.linkTitle': 'লিংকের শিরোনাম',
        'course.meetingUrl': 'মিটিং URL',
        'course.schedule': 'সময়সূচী',
        'course.resourceTitle': 'সম্পদের শিরোনাম',
        'course.resourceUrl': 'সম্পদের URL',
        'course.resourceType': 'সম্পদের ধরণ',
        'course.youtube': 'ইউটিউব',
        'course.document': 'ডকুমেন্ট',
        'course.website': 'ওয়েবসাইট',
        'course.noModules': 'কোনো মডিউল যোগ করা হয়নি',
        'course.noLinks': 'কোনো ক্লাস লিংক যোগ করা হয়নি',
        'course.noResources': 'কোনো সম্পদ যোগ করা হয়নি',
        'course.noEnrolledStudents': 'এখনও কোনো শিক্ষার্থী ভর্তি হয়নি',
        'course.enrollmentDate': 'ভর্তির তারিখ',
        'course.progress': 'অগ্রগতি',
        'course.lastActivity': 'শেষ কার্যকলাপ',
        'course.completed': 'সম্পূর্ণ',
        'course.inProgress': 'চলমান',
        'course.notStarted': 'শুরু হয়নি',

        // Dashboard
        'dashboard.welcome': 'স্বাগতম',
        'dashboard.welcomeBack': 'আবার স্বাগতম',
        'dashboard.continueJourney': 'আপনার জাপানি ভাষা শেখার যাত্রা ব্যক্তিগত পাঠের সাথে চালিয়ে যান',
        'dashboard.continueLearning': 'শেখা চালিয়ে যান',
        'dashboard.home': 'হোম',
        'dashboard.signOut': 'সাইন আউট',
        'dashboard.loading': 'ড্যাশবোর্ড লোড হচ্ছে...',
        'dashboard.studyStreak': 'অধ্যয়নের ধারা',
        'dashboard.daysInRow': 'দিন পরপর',
        'dashboard.totalCourses': 'মোট কোর্স',
        'dashboard.enrolledCourses': 'ভর্তি হওয়া কোর্স',
        'dashboard.lessonsCompleted': 'সম্পূর্ণ হওয়া পাঠ',
        'dashboard.lessonsFinished': 'সমাপ্ত পাঠ',
        'dashboard.wordsLearned': 'শেখা শব্দ',
        'dashboard.vocabularyMastered': 'আয়ত্ত করা শব্দভাণ্ডার',
        'dashboard.myCourses': 'আমার কোর্সগুলি',
        'dashboard.schedule': 'সময়সূচী',
        'dashboard.profile': 'প্রোফাইল',
        'dashboard.progress': 'অগ্রগতি',
        'dashboard.learningProgress': 'শেখার অগ্রগতি',
        'dashboard.trackJourney': 'আপনার জাপানি ভাষা শেখার যাত্রা এবং অর্জনগুলি ট্র্যাক করুন',
        'dashboard.currentLevel': 'বর্তমান স্তর',
        'dashboard.studyTime': 'অধ্যয়নের সময়',
        'dashboard.accuracyRate': 'নির্ভুলতার হার',
        'dashboard.comingSoon': 'শীঘ্রই আসছে',
        'dashboard.beginner': 'শিক্ষানবিস',
        'dashboard.intermediate': 'মধ্যম',
        'dashboard.advanced': 'উন্নত',

        // Enrolled Courses
        'courses.myEnrolledCourses': 'আমার ভর্তি হওয়া কোর্সগুলি',
        'courses.continueLearning': 'আপনার ভর্তি হওয়া কোর্সগুলি দিয়ে শেখা চালিয়ে যান',
        'courses.noCourses': 'আপনি এখনও কোনো কোর্সে ভর্তি হননি',
        'courses.browseAndEnroll': 'আমাদের বিস্তৃত কোর্স নির্বাচন ব্রাউজ করুন এবং আজই শুরু করুন!',
        'courses.browseCourses': 'কোর্স ব্রাউজ করুন',
        'courses.progress': 'অগ্রগতি',
        'courses.nextClass': 'পরবর্তী ক্লাস',
        'courses.joinClass': 'ক্লাসে যোগ দিন',
        'courses.continueStudying': 'অধ্যয়ন চালিয়ে যান',
        'courses.students': 'শিক্ষার্থী',
        'courses.lessons': 'পাঠ',
        'courses.completed': 'সম্পূর্ণ',
        'courses.viewCurriculum': 'পাঠ্যক্রম দেখুন',

        // Form Labels
        'form.title': 'শিরোনাম',
        'form.description': 'বিবরণ',
        'form.level': 'স্তর',
        'form.category': 'বিভাগ',
        'form.duration': 'সময়কাল',
        'form.difficulty': 'কঠিনতা',
        'form.premium': 'প্রিমিয়াম',
        'form.published': 'প্রকাশিত',
        'form.learningObjectives': 'শেখার উদ্দেশ্য',
        'form.links': 'লিংকসমূহ',
        'form.thumbnailUrl': 'থাম্বনেইল URL',
        'form.estimatedDuration': 'আনুমানিক সময়কাল (মিনিট)',
        'form.difficultyLevel': 'কঠিনতা (১-১০)',
        'form.learningObjectivesDesc': 'শিক্ষার্থীরা এই কোর্স থেকে কী শিখবে?',
        'form.learningObjectiveNum': 'শেখার উদ্দেশ্য',
        'form.addObjective': 'উদ্দেশ্য যোগ করুন',
        'form.linksDesc': 'এই কোর্সের জন্য দরকারী লিংক যোগ করুন',
        'form.addLink': 'লিংক যোগ করুন',
        'form.thumbnailUrlOptional': 'থাম্বনেইল URL (ঐচ্ছিক)',
        'form.instructorNotesOptional': 'প্রশিক্ষকের নোট (ঐচ্ছিক)',
        'form.premiumCourse': 'প্রিমিয়াম কোর্স',
        'form.thumbnailPlaceholder': 'https://example.com/image.jpg',
        'form.instructorNotesPlaceholder': 'প্রশিক্ষকদের জন্য অতিরিক্ত নোট...',
        'form.whatYoullLearn': 'আপনি কী শিখবেন',
        'form.whatYoullLearnPlaceholder': 'শিক্ষার্থীরা এই কোর্স থেকে কী শিখবে...',
        'form.courseLessonModule': 'কোর্স পাঠ মডিউল',
        'form.courseLessonModulePlaceholder': 'কোর্সের পাঠ্যক্রম, পাঠ এবং মডিউল বর্ণনা করুন...',
        'form.actualPrice': 'প্রকৃত মূল্য',
        'form.discountedPrice': 'ছাড়ের মূল্য',
        'form.enrollmentLastDate': 'ভর্তির শেষ তারিখ',
        'admin.addNewCourse': 'নতুন কোর্স যোগ করুন',
        'admin.createNewCourseDesc': 'একটি নতুন জাপানি ভাষার কোর্স তৈরি করুন',
        'admin.allCourses': 'সব কোর্স',
        'admin.manageCourses': 'আপনার জাপানি ভাষার কোর্সগুলি পরিচালনা করুন',
        'admin.filterSearch': 'ফিল্টার ও অনুসন্ধান',
        'admin.searchCourses': 'কোর্স অনুসন্ধান করুন',
        'admin.searchPlaceholder': 'কোর্সের নাম, বিবরণ দিয়ে অনুসন্ধান করুন...',
        'admin.status': 'অবস্থা',
        'admin.level': 'স্তর',
        'admin.category': 'বিভাগ',
        'admin.allStatus': 'সব অবস্থা',
        'admin.allLevels': 'সব স্তর',
        'admin.allCategories': 'সব বিভাগ',
        'admin.published': 'প্রকাশিত',
        'admin.draft': 'খসড়া',
        'admin.yourCourses': 'আপনার কোর্সগুলি',
        'admin.showingCourses': 'দেখানো হচ্ছে',
        'admin.ofCourses': 'এর মধ্যে',
        'admin.coursesText': 'কোর্স',
        'admin.addCourse': 'কোর্স যোগ করুন',
        'admin.noCourses': 'কোনো কোর্স পাওয়া যায়নি',
        'admin.createFirstCourse': 'আপনার প্রথম কোর্স তৈরি করুন',
        'admin.premium': 'প্রিমিয়াম',
        'admin.vocabulary': 'শব্দভান্ডার',
        'admin.grammar': 'ব্যাকরণ',
        'admin.kanji': 'কাঞ্জি',
        'admin.conversation': 'কথোপকথন',
        'admin.culture': 'সংস্কৃতি',
        'admin.reading': 'পড়া',
        'admin.writing': 'লেখা',
        'admin.difficulty': 'কঠিনতা',
        'admin.studentsCount': 'শিক্ষার্থী',
        'admin.view': 'দেখুন',
        'admin.edit': 'সম্পাদনা',
        'admin.deleteConfirm': 'আপনি কি নিশ্চিত যে আপনি কোর্স মুছে ফেলতে চান',
        'admin.courseDeleted': 'কোর্স মুছে ফেলা হয়েছে',
        'admin.failedToDelete': 'কোর্স মুছে ফেলতে ব্যর্থ',
        'admin.backToCourses': 'কোর্সে ফিরে যান',
        'admin.courseDetails': 'কোর্সের বিবরণ',
        'admin.courseOverview': 'কোর্স সংক্ষিপ্ত বিবরণ',
        'admin.essentialInfo': 'অত্যাবশ্যক কোর্সের তথ্য',
        'admin.description': 'বিবরণ',
        'admin.courseDetailsSection': 'কোর্সের বিস্তারিত',
        'admin.technicalSpecs': 'প্রযুক্তিগত বৈশিষ্ট্য এবং মেটাডেটা',
        'admin.learningObjectivesSection': 'শেখার উদ্দেশ্য',
        'admin.whatStudentsAchieve': 'শিক্ষার্থীরা কী অর্জন করবে',
        'admin.statusSettings': 'অবস্থা ও সেটিংস',
        'admin.publication': 'প্রকাশনা',
        'admin.access': 'অ্যাক্সেস',
        'admin.free': 'বিনামূল্যে',
        'admin.timeline': 'সময়রেখা',
        'admin.created': 'তৈরি হয়েছে',
        'admin.quickActions': 'দ্রুত কর্ম',
        'admin.previewCourse': 'কোর্স প্রিভিউ করুন',
        'admin.viewStudents': 'শিক্ষার্থী দেখুন',
        'admin.duplicateCourse': 'কোর্স অনুলিপি করুন',
        'admin.minutes': 'মিনিট',
        'admin.courseTags': 'কোর্স ট্যাগ',
        'admin.prerequisites': 'পূর্বশর্ত',
        'admin.prerequisitesDesc': 'শিক্ষার্থীদের আগে থেকে কী জানতে হবে',
        'admin.updateCourse': 'আপনার জাপানি ভাষার কোর্স আপডেট করুন',
        'admin.updateJapaneseLanguageCourse': 'আপনার জাপানি ভাষার কোর্স আপডেট করুন',
        'admin.courseInformation': 'কোর্সের তথ্য',
        'admin.basicDetails': 'আপনার কোর্স সম্পর্কে মৌলিক বিবরণ',
        'admin.jlptLevel': 'JLPT স্তর',
        'admin.actualPrice': 'প্রকৃত মূল্য',
        'admin.discountedPrice': 'ছাড়ের মূল্য',
        'admin.enrollmentLastDate': 'ভর্তির শেষ তারিখ',
        'admin.whatYoullLearn': 'আপনি যা শিখবেন',
        'admin.courseLessonModule': 'কোর্স পাঠ / মডিউল / পাঠ্যক্রম',
        'admin.estimatedDuration': 'আনুমানিক সময়কাল (মিনিট)',
        'admin.learningObjectives': 'শেখার উদ্দেশ্য',
        'admin.learningObjectivesDesc': 'শিক্ষার্থীরা এই কোর্স থেকে কী শিখবে?',
        'admin.learningObjectivePlaceholder': 'শেখার উদ্দেশ্য',
        'admin.addObjective': 'উদ্দেশ্য যোগ করুন',
        'admin.links': 'লিংকসমূহ',
        'admin.linksDesc': 'এই কোর্সের জন্য উপযোগী লিংক যোগ করুন',
        'admin.addLink': 'লিংক যোগ করুন',
        'admin.thumbnailUrl': 'থাম্বনেইল URL (ঐচ্ছিক)',
        'admin.instructorNotes': 'প্রশিক্ষকের নোট (ঐচ্ছিক)',
        'admin.instructorNotesPlaceholder': 'প্রশিক্ষকদের জন্য অতিরিক্ত নোট...',
        'admin.premiumCourse': 'প্রিমিয়াম কোর্স',
        'admin.saveAsDraft': 'খসড়া হিসেবে সংরক্ষণ',
        'admin.saveAndPublish': 'সংরক্ষণ ও প্রকাশ',
        'admin.courseTitlePlaceholder': 'যেমন. Japan101 - হিরাগানার মূল বিষয়',
        'admin.descriptionPlaceholder': 'শিক্ষার্থীরা এই কোর্সে কী শিখবে তা বর্ণনা করুন...',
        'admin.whatYoullLearnPlaceholder': 'শিক্ষার্থীরা এই কোর্স থেকে কী শিখবে...',
        'admin.courseLessonModulePlaceholder': 'কোর্সের পাঠ্যক্রম, পাঠ এবং মডিউল বর্ণনা করুন...',

        // Currency
        'currency.bdt': 'টাকা',
        'currency.symbol': '৳',
        'currency.code': 'BDT',

        // Common
        'common.loading': 'লোড হচ্ছে...',
        'common.error': 'ত্রুটি',
        'common.success': 'সফল',
        'common.warning': 'সতর্কতা',
        'common.info': 'তথ্য',
        'common.confirm': 'নিশ্চিত করুন',
        'common.yes': 'হ্যাঁ',
        'common.no': 'না',
        'common.ok': 'ঠিক আছে',
        'common.close': 'বন্ধ করুন',
        'common.next': 'পরবর্তী',
        'common.previous': 'পূর্ববর্তী',
        'common.submit': 'জমা দিন',
        'common.reset': 'রিসেট',
        'common.search': 'অনুসন্ধান',
        'common.filter': 'ফিল্টার',
        'common.sort': 'সাজান',
        'common.edit': 'সম্পাদনা',
        'common.view': 'দেখুন',
        'common.download': 'ডাউনলোড',
        'common.upload': 'আপলোড',
    },
    en: {
        // Navigation
        'nav.features': 'Features',
        'nav.products': 'Blog',
        'nav.resources': 'Resources',
        'nav.contact': 'Contact',
        'nav.startForFree': 'Start for free',
        'nav.getStarted': 'Get Started',
        'nav.login': 'Login',
        'nav.signUp': 'Sign Up',

        // Hero Section
        'hero.title': 'Master Japanese Language Learning',
        'hero.subtitle': 'Learn Japanese with our modern platform. Complete courses from Hiragana to Kanji.',
        'hero.cta': 'Get Started Today',
        'hero.watchDemo': 'Watch Demo',

        // Features Section
        'features.title': 'Our Features',
        'features.subtitle': 'Everything you need to learn Japanese',
        'features.interactive.title': 'Interactive Lessons',
        'features.interactive.description': 'Learn Japanese through engaging interactive lessons',
        'features.progress.title': 'Progress Tracking',
        'features.progress.description': 'Track your learning progress and achieve your goals',
        'features.community.title': 'Community Support',
        'features.community.description': 'Join other learners and learn together',

        // Courses Section
        'courses.title': 'Our Courses',
        'courses.subtitle': 'Choose the right course for your level',
        'courses.beginner': 'Beginner',
        'courses.intermediate': 'Intermediate',
        'courses.advanced': 'Advanced',
        'courses.enrollNow': 'Enroll Now',
        'courses.viewDetails': 'View Details',

        // Pricing Section
        'pricing.title': 'Pricing Plans',
        'pricing.subtitle': 'Choose the best package for your budget',
        'pricing.free': 'Free',
        'pricing.premium': 'Premium',
        'pricing.month': '/month',
        'pricing.year': '/year',
        'pricing.choosePlan': 'Choose Plan',
        'pricing.noCreditCard': 'No credit card required',
        'pricing.upgradeAnytime': 'Upgrade anytime • No commitments',
        'pricing.cancelAnytime': 'Cancel anytime • 30-day money-back guarantee',
        'pricing.oneTimePayment': 'One-time payment • Lifetime updates included',
        'pricing.guarantee': '30-day money-back guarantee',
        'pricing.securePayment': 'Secure payment processing',
        'pricing.satisfiedLearners': '10,000+ satisfied learners',
        'pricing.trustText': 'Join thousands of successful Japanese learners who have transformed their language skills with our proven methodology and expert guidance.',

        // Footer Section
        'footer.newsletter.title': 'Stay Updated with Japanese Learning Tips',
        'footer.newsletter.subtitle': 'Get weekly insights, study tips, and exclusive content delivered to your inbox.',
        'footer.newsletter.community': 'Join our community of passionate Japanese learners!',
        'footer.newsletter.placeholder': 'Enter your email address',
        'footer.newsletter.subscribe': 'Subscribe',
        'footer.newsletter.noSpam': 'No spam, unsubscribe anytime. 10,000+ subscribers trust us.',
        'footer.brand.description': 'Master Japanese language with our comprehensive online courses, AI-powered practice, and expert guidance. Transform your language learning journey today.',
        'footer.contact.email': 'support@japaneseshikhi.com',
        'footer.contact.phone': '+1 (555) 123-4567',
        'footer.contact.available': 'Available worldwide',
        'footer.rating': '4.9/5 Rating',
        'footer.students': '10,000+ Students',
        'footer.certified': 'Certified Teachers',
        'footer.quickLinks': 'Quick Links',
        'footer.courses': 'Courses',
        'footer.support': 'Support',
        'footer.followUs': 'Follow Us',
        'footer.aboutUs': 'About Us',
        'footer.howItWorks': 'How It Works',
        'footer.successStories': 'Success Stories',
        'footer.blog': 'Blog',
        'footer.beginnerJapanese': 'Beginner Japanese',
        'footer.intermediateJapanese': 'Intermediate Japanese',
        'footer.advancedJapanese': 'Advanced Japanese',
        'footer.businessJapanese': 'Business Japanese',
        'footer.jlptPreparation': 'JLPT Preparation',
        'footer.conversationPractice': 'Conversation Practice',
        'footer.popular': 'Popular',
        'footer.new': 'New',
        'footer.helpCenter': 'Help Center',
        'footer.contactSupport': 'Contact Support',
        'footer.communityForum': 'Community Forum',
        'footer.privacyPolicy': 'Privacy Policy',
        'footer.termsOfService': 'Terms of Service',
        'footer.refundPolicy': 'Refund Policy',
        'footer.copyright': '© 2025 Japanese Shikhi. All rights reserved.',
        'footer.madeWith': 'Made with Love for Japanese learners',
        'footer.privacyLink': 'Privacy',
        'footer.termsLink': 'Terms',
        'footer.cookies': 'Cookies',

        // Testimonials
        'testimonials.title': 'Student Reviews',
        'testimonials.subtitle': 'What our successful students say',

        // Admin Dashboard
        'admin.dashboard': 'Dashboard',
        'admin.dashboardOverview': 'Overview of your Japanese language courses',
        'admin.totalCourses': 'Total Courses',
        'admin.totalStudents': 'Total Students',
        'admin.totalRevenue': 'Total Revenue',
        'admin.courseCompletion': 'Course Completion',
        'admin.coursesCreated': 'courses created',
        'admin.studentsEnrolled': 'students enrolled',
        'admin.noRevenue': 'No revenue generated',
        'admin.noCompletions': 'No completions yet',
        'admin.noCoursesCreated': 'No courses created yet',
        'admin.noEnrollments': 'No enrollments yet',
        'admin.recentActivity': 'Recent Activity',
        'admin.latestActivity': 'Latest course and student activity',
        'admin.noRecentActivity': 'No recent activity to display',
        'admin.japaneseShikhi': 'Japanese Shikhi',
        'admin.adminPanel': 'Admin Panel',
        'admin.welcome': 'Welcome',
        'admin.home': 'Home',
        'admin.users': 'Users',
        'admin.courses': 'Courses',
        'admin.students': 'Students',
        'admin.analytics': 'Analytics',
        'admin.settings': 'Settings',
        'admin.createCourse': 'Create New Course',
        'admin.editCourse': 'Edit Course',
        'admin.courseTitle': 'Course Title',
        'admin.courseDescription': 'Course Description',
        'admin.save': 'Save',
        'admin.cancel': 'Cancel',
        'admin.delete': 'Delete',

        // Users Page
        'users.title': 'Students & Users',
        'users.subtitle': 'Manage enrolled students and track their progress',
        'users.exportData': 'Export Data',
        'users.sendNotification': 'Send Notification',
        'users.totalUsers': 'Total Users',
        'users.activeUsers': 'Active Users',
        'users.premiumUsers': 'Premium Users',
        'users.noUsersYet': 'No users yet',
        'users.noActiveUsers': 'No active users',
        'users.noPremiumUsers': 'No premium users',
        'users.noRevenueYet': 'No revenue yet',
        'users.searchAndFilter': 'Search & Filter Users',
        'users.searchUsers': 'Search users',
        'users.searchPlaceholder': 'Search by name or email...',
        'users.status': 'Status',
        'users.subscription': 'Subscription',
        'users.allStatus': 'All Status',
        'users.allTypes': 'All Types',
        'users.active': 'Active',
        'users.inactive': 'Inactive',
        'users.free': 'Free',
        'users.premium': 'Premium',
        'users.allUsers': 'All Users',
        'users.enrollmentTracking': 'Student enrollment and progress tracking',
        'users.noUsersFound': 'No users found',
        'users.willAppearHere': 'Users will appear here when they sign up for your courses',
        'users.exporting': 'Exporting...',
        'users.exportSuccess': 'Data exported successfully',
        'users.exportTemplateSuccess': 'Template downloaded successfully',
        'users.exportError': 'Error exporting data',
        'users.users': 'users',
        'users.activeUsersText': 'active users',
        'users.premiumUsersText': 'premium users',
        'users.revenueGenerated': 'Revenue generated',

        // Course Management
        'course.management': 'Course Management',
        'course.createAndManage': 'Create and manage Japanese courses',
        'course.addNewCourse': 'Add New Course',
        'course.createNewCourse': 'Create New Course',
        'course.basicDetails': 'Basic details about your course',
        'course.courseTitle': 'Course Title',
        'course.titlePlaceholder': 'e.g., Beginner Japanese Grammar',
        'course.level': 'Level',
        'course.beginner': 'Beginner',
        'course.intermediate': 'Intermediate',
        'course.advanced': 'Advanced',
        'course.description': 'Description',
        'course.descriptionPlaceholder': 'Describe what students will learn in this course...',
        'course.difficulty': 'Difficulty',
        'course.easy': 'Easy',
        'course.medium': 'Medium',
        'course.hard': 'Hard',
        'course.cancel': 'Cancel',
        'course.createCourse': 'Create Course',
        'course.allCourses': 'All Courses',
        'course.manageCatalog': 'Manage your course catalog and track enrollments',
        'course.noCoursesFound': 'No courses found. Create your first course to get started.',
        'course.published': 'Published',
        'course.draft': 'Draft',
        'course.students': 'students',
        'course.created': 'Created',
        'course.view': 'View',
        'course.edit': 'Edit',
        'course.delete': 'Delete',
        'course.details': 'Course Details',
        'course.modules': 'Class Modules',
        'course.classLinks': 'Class Links',
        'course.resources': 'Resources & YouTube',
        'course.enrolledStudents': 'Enrolled Students',
        'course.assignments': 'Assignments & Quiz',
        'course.addModule': 'Add Module',
        'course.addClassLink': 'Add Class Link',
        'course.addResource': 'Add Resource',
        'course.moduleTitle': 'Module Title',
        'course.moduleContent': 'Module Content',
        'course.moduleOrder': 'Module Order',
        'course.linkTitle': 'Link Title',
        'course.meetingUrl': 'Meeting URL',
        'course.schedule': 'Schedule',
        'course.resourceTitle': 'Resource Title',
        'course.resourceUrl': 'Resource URL',
        'course.resourceType': 'Resource Type',
        'course.youtube': 'YouTube',
        'course.document': 'Document',
        'course.website': 'Website',
        'course.noModules': 'No modules added yet',
        'course.noLinks': 'No class links added yet',
        'course.noResources': 'No resources added yet',
        'course.noEnrolledStudents': 'No students enrolled yet',
        'course.enrollmentDate': 'Enrollment Date',
        'course.progress': 'Progress',
        'course.lastActivity': 'Last Activity',
        'course.completed': 'Completed',
        'course.inProgress': 'In Progress',
        'course.notStarted': 'Not Started',

        // Dashboard
        'dashboard.welcome': 'Welcome',
        'dashboard.welcomeBack': 'Welcome back',
        'dashboard.continueJourney': 'Continue your Japanese learning journey with personalized lessons',
        'dashboard.continueLearning': 'Continue Learning',
        'dashboard.home': 'Home',
        'dashboard.signOut': 'Sign Out',
        'dashboard.loading': 'Loading dashboard...',
        'dashboard.studyStreak': 'Study Streak',
        'dashboard.daysInRow': 'days in a row',
        'dashboard.totalCourses': 'Total Courses',
        'dashboard.enrolledCourses': 'enrolled courses',
        'dashboard.lessonsCompleted': 'Lessons Completed',
        'dashboard.lessonsFinished': 'lessons finished',
        'dashboard.wordsLearned': 'Words Learned',
        'dashboard.vocabularyMastered': 'vocabulary mastered',
        'dashboard.myCourses': 'My Courses',
        'dashboard.schedule': 'Schedule',
        'dashboard.profile': 'Profile',
        'dashboard.progress': 'Progress',
        'dashboard.learningProgress': 'Learning Progress',
        'dashboard.trackJourney': 'Track your Japanese learning journey and achievements',
        'dashboard.currentLevel': 'Current Level',
        'dashboard.studyTime': 'Study Time',
        'dashboard.accuracyRate': 'Accuracy Rate',
        'dashboard.comingSoon': 'Coming Soon',
        'dashboard.beginner': 'Beginner',
        'dashboard.intermediate': 'Intermediate',
        'dashboard.advanced': 'Advanced',

        // Enrolled Courses
        'courses.myEnrolledCourses': 'My Enrolled Courses',
        'courses.continueLearning': 'Continue learning with your enrolled courses',
        'courses.noCourses': 'You haven\'t enrolled in any courses yet',
        'courses.browseAndEnroll': 'Browse our extensive course selection and get started today!',
        'courses.browseCourses': 'Browse Courses',
        'courses.progress': 'Progress',
        'courses.nextClass': 'Next Class',
        'courses.joinClass': 'Join Class',
        'courses.continueStudying': 'Continue Studying',
        'courses.students': 'students',
        'courses.lessons': 'lessons',
        'courses.completed': 'completed',
        'courses.viewCurriculum': 'View Curriculum',

        // Form Labels
        'form.title': 'Title',
        'form.description': 'Description',
        'form.level': 'Level',
        'form.category': 'Category',
        'form.duration': 'Duration',
        'form.difficulty': 'Difficulty',
        'form.premium': 'Premium',
        'form.published': 'Published',
        'form.learningObjectives': 'Learning Objectives',
        'form.links': 'Links',
        'form.thumbnailUrl': 'Thumbnail URL',
        'form.estimatedDuration': 'Estimated Duration (minutes)',
        'form.difficultyLevel': 'Difficulty (1-10)',
        'form.learningObjectivesDesc': 'What will students learn from this course?',
        'form.learningObjectiveNum': 'Learning Objective',
        'form.addObjective': 'Add Objective',
        'form.linksDesc': 'Add useful links for this course',
        'form.addLink': 'Add Link',
        'form.thumbnailUrlOptional': 'Thumbnail URL (optional)',
        'form.instructorNotesOptional': 'Instructor Notes (optional)',
        'form.premiumCourse': 'Premium Course',
        'form.thumbnailPlaceholder': 'https://example.com/image.jpg',
        'form.instructorNotesPlaceholder': 'Additional notes for instructors...',
        'form.whatYoullLearn': 'What You will Learn',
        'form.whatYoullLearnPlaceholder': 'What will students learn from this course...',
        'form.courseLessonModule': 'Course Lesson Module',
        'form.courseLessonModulePlaceholder': 'Describe the course curriculum, lessons, and modules...',
        'form.actualPrice': 'Actual Price',
        'form.discountedPrice': 'Discounted Price',
        'form.enrollmentLastDate': 'Enrollment Last Date',
        'admin.addNewCourse': 'Add New Course',
        'admin.createNewCourseDesc': 'Create a new Japanese language course',
        'admin.allCourses': 'All Courses',
        'admin.manageCourses': 'Manage your Japanese language courses',
        'admin.filterSearch': 'Filter & Search',
        'admin.searchCourses': 'Search courses',
        'admin.searchPlaceholder': 'Search by course name, description...',
        'admin.status': 'Status',
        'admin.level': 'Level',
        'admin.category': 'Category',
        'admin.allStatus': 'All Status',
        'admin.allLevels': 'All Levels',
        'admin.allCategories': 'All Categories',
        'admin.published': 'Published',
        'admin.draft': 'Draft',
        'admin.yourCourses': 'Your Courses',
        'admin.showingCourses': 'Showing',
        'admin.ofCourses': 'of',
        'admin.coursesText': 'courses',
        'admin.addCourse': 'Add Course',
        'admin.noCourses': 'No courses found',
        'admin.createFirstCourse': 'Create Your First Course',
        'admin.premium': 'Premium',
        'admin.vocabulary': 'Vocabulary',
        'admin.grammar': 'Grammar',
        'admin.kanji': 'Kanji',
        'admin.conversation': 'Conversation',
        'admin.culture': 'Culture',
        'admin.reading': 'Reading',
        'admin.writing': 'Writing',
        'admin.difficulty': 'Difficulty',
        'admin.studentsCount': 'students',
        'admin.view': 'View',
        'admin.edit': 'Edit',
        'admin.deleteConfirm': 'Are you sure you want to delete course',
        'admin.courseDeleted': 'Course deleted',
        'admin.failedToDelete': 'Failed to delete course',
        'admin.backToCourses': 'Back to Courses',
        'admin.courseDetails': 'Course Details',
        'admin.courseOverview': 'Course Overview',
        'admin.essentialInfo': 'Essential course information',
        'admin.description': 'Description',
        'admin.courseDetailsSection': 'Course Details',
        'admin.technicalSpecs': 'Technical specifications and metadata',
        'admin.learningObjectivesSection': 'Learning Objectives',
        'admin.whatStudentsAchieve': 'What students will achieve',
        'admin.statusSettings': 'Status & Settings',
        'admin.publication': 'Publication',
        'admin.access': 'Access',
        'admin.free': 'Free',
        'admin.timeline': 'Timeline',
        'admin.created': 'Created',
        'admin.quickActions': 'Quick Actions',
        'admin.previewCourse': 'Preview Course',
        'admin.viewStudents': 'View Students',
        'admin.duplicateCourse': 'Duplicate Course',
        'admin.minutes': 'minutes',
        'admin.courseTags': 'Course Tags',
        'admin.prerequisites': 'Prerequisites',
        'admin.prerequisitesDesc': 'What students need to know beforehand',
        'admin.updateCourse': 'Update your Japanese language course',
        'admin.updateJapaneseLanguageCourse': 'Update your Japanese language course',
        'admin.courseInformation': 'Course Information',
        'admin.basicDetails': 'Basic details about your course',
        'admin.jlptLevel': 'JLPT Level',
        'admin.actualPrice': 'Actual price',
        'admin.discountedPrice': 'Discounted Price',
        'admin.enrollmentLastDate': 'Enrollment last date',
        'admin.whatYoullLearn': 'What you\'ll learn',
        'admin.courseLessonModule': 'Course Lesson / Module / Curriculum',
        'admin.estimatedDuration': 'Estimated Duration (minutes)',
        'admin.learningObjectives': 'Learning Objectives',
        'admin.learningObjectivesDesc': 'What will students learn from this course?',
        'admin.learningObjectivePlaceholder': 'Learning objective',
        'admin.addObjective': 'Add Objective',
        'admin.links': 'Links',
        'admin.linksDesc': 'Add useful links for this course',
        'admin.addLink': 'Add Link',
        'admin.thumbnailUrl': 'Thumbnail URL (optional)',
        'admin.instructorNotes': 'Instructor Notes (optional)',
        'admin.instructorNotesPlaceholder': 'Additional notes for instructors...',
        'admin.premiumCourse': 'Premium Course',
        'admin.saveAsDraft': 'Save as Draft',
        'admin.saveAndPublish': 'Save & Publish',
        'admin.courseTitlePlaceholder': 'e.g. Japan101 - Hiragana Basics',
        'admin.descriptionPlaceholder': 'Describe what students will learn in this course...',
        'admin.whatYoullLearnPlaceholder': 'What will students learn from this course...',
        'admin.courseLessonModulePlaceholder': 'Describe the course curriculum, lessons, and modules...',

        // Currency
        'currency.bdt': 'Taka',
        'currency.symbol': '৳',
        'currency.code': 'BDT',

        // Common
        'common.loading': 'Loading...',
        'common.error': 'Error',
        'common.success': 'Success',
        'common.warning': 'Warning',
        'common.info': 'Info',
        'common.confirm': 'Confirm',
        'common.yes': 'Yes',
        'common.no': 'No',
        'common.ok': 'OK',
        'common.close': 'Close',
        'common.next': 'Next',
        'common.previous': 'Previous',
        'common.submit': 'Submit',
        'common.reset': 'Reset',
        'common.search': 'Search',
        'common.filter': 'Filter',
        'common.sort': 'Sort',
        'common.edit': 'Edit',
        'common.view': 'View',
        'common.download': 'Download',
        'common.upload': 'Upload',
    }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
    const [language, setLanguageState] = useState<Language>('bn');

    // Load language from localStorage on mount
    useEffect(() => {
        if (typeof window !== 'undefined') {
            const savedLanguage = localStorage.getItem('language') as Language;
            if (savedLanguage && (savedLanguage === 'bn' || savedLanguage === 'en')) {
                setLanguageState(savedLanguage);
            }
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        if (typeof window !== 'undefined') {
            localStorage.setItem('language', lang);
        }
    };

    const t = (key: string): string => {
        return (translations[language] as any)[key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        // During SSR or if provider is missing, return default values
        return {
            language: 'en' as Language,
            setLanguage: () => {},
            t: (key: string) => key
        };
    }
    return context;
}